# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: dhrutigandhi
# "service" is the name of this project. This will also be added to your AWS resource names.
service: InstaChat

provider:
  name: aws
  runtime: nodejs20.x
  lambdaHashingVersion: 20201221

functions:
   websocketHandler:
    handler: src/handler.handle
    events:
      - websocket:
          route: $connect # when user connects
      - websocket:
          route: $disconnect # when user disconnects
      - websocket:
          route: getMessages 
      - websocket:
          route: sendMessage
      - websocket: 
          route: getClients

plugins:
  - serverless-plugin-typescript

resources:
  Resources:
    ClientsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Clients
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        AttributeDefinitions:
          - AttributeName: connectionId
            AttributeType: S
          - AttributeName: nickname
            AttributeType: S
